"""Train and export the fixed-hash six-way offline wish classifier."""

from __future__ import annotations

import base64
import csv
import json
import math
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "generated"
LABELS = ("safety", "reunion", "courage", "abundance", "joy", "longevity")
FEATURE_COUNT = 8192
MODEL_VERSION = "wish-classifier-1.0.0-20260824"


def fnv1a(text: str) -> int:
    value = 0x811C9DC5
    for byte in text.encode("utf-8"):
        value ^= byte
        value = (value * 0x01000193) & 0xFFFFFFFF
    return value


def features(text: str) -> dict[int, float]:
    normalized = text.lower()
    characters = list(normalized)
    counts: dict[int, float] = {}
    for size in (1, 2, 3):
        for index in range(len(characters) - size + 1):
            token = f"c{size}:{''.join(characters[index:index + size])}"
            hashed = fnv1a(token) % FEATURE_COUNT
            counts[hashed] = counts.get(hashed, 0.0) + 1.0
    current = []
    for character in normalized + " ":
        if "a" <= character <= "z" or (character == "'" and current):
            current.append(character)
        elif current:
            token = f"w:{''.join(current).strip(chr(39))}"
            if token != "w:":
                hashed = fnv1a(token) % FEATURE_COUNT
                counts[hashed] = counts.get(hashed, 0.0) + 1.0
            current = []
    norm = math.sqrt(sum(value * value for value in counts.values())) or 1.0
    return {index: value / norm for index, value in counts.items()}


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def matrix(rows: list[dict[str, str]]) -> np.ndarray:
    result = np.zeros((len(rows), FEATURE_COUNT), dtype=np.float32)
    for row_index, row in enumerate(rows):
        for feature_index, value in features(row["text"]).items():
            result[row_index, feature_index] = value
    return result


def softmax(logits: np.ndarray) -> np.ndarray:
    shifted = logits - logits.max(axis=1, keepdims=True)
    values = np.exp(shifted)
    return values / values.sum(axis=1, keepdims=True)


def train(x: np.ndarray, y: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    rng = np.random.default_rng(20260824)
    weights = rng.normal(0.0, 0.002, (len(LABELS), FEATURE_COUNT)).astype(np.float32)
    intercepts = np.zeros(len(LABELS), dtype=np.float32)
    one_hot = np.eye(len(LABELS), dtype=np.float32)[y]
    sample_weight = np.ones(len(y), dtype=np.float32)
    # Ambiguous examples are duplicated across labels; a modest weight preserves their
    # low-confidence calibration without drowning out the semantic examples.
    sample_weight[-240:] = 0.55
    sample_weight /= sample_weight.mean()

    for epoch in range(420):
        probabilities = softmax(x @ weights.T + intercepts)
        error = (probabilities - one_hot) * sample_weight[:, None]
        learning_rate = 28.0 / (1.0 + epoch * 0.008)
        gradient = (error.T @ x) / len(y) + 0.00005 * weights
        bias_gradient = error.mean(axis=0)
        weights -= learning_rate * gradient.astype(np.float32)
        intercepts -= learning_rate * bias_gradient.astype(np.float32)
    return weights, intercepts


def macro_f1(expected: list[str], predicted: list[str]) -> float:
    scores = []
    for label in LABELS:
        tp = sum(a == label and b == label for a, b in zip(expected, predicted))
        fp = sum(a != label and b == label for a, b in zip(expected, predicted))
        fn = sum(a == label and b != label for a, b in zip(expected, predicted))
        precision = tp / (tp + fp) if tp + fp else 0.0
        recall = tp / (tp + fn) if tp + fn else 0.0
        scores.append(2 * precision * recall / (precision + recall) if precision + recall else 0.0)
    return float(sum(scores) / len(scores))


def export_model(weights: np.ndarray, intercepts: np.ndarray) -> None:
    payload = base64.b64encode(np.ascontiguousarray(weights.astype("<f4")).tobytes()).decode("ascii")
    checksum = f"{fnv1a(payload):08x}"
    source = f'''// Generated by scripts/train_classifier.py. Do not edit by hand.\nexport const MODEL_VERSION = "{MODEL_VERSION}";\nexport const FEATURE_COUNT = {FEATURE_COUNT};\nexport const MODEL_LABELS = ["safety", "reunion", "courage", "abundance", "joy", "longevity"] as const;\nexport const MODEL_WEIGHTS_BASE64 = "{payload}";\nexport const MODEL_WEIGHTS_CHECKSUM = "{checksum}";\nexport const MODEL_INTERCEPTS = [{", ".join(f"{value:.9g}" for value in intercepts)}] as const;\n'''
    (ROOT / "src" / "core" / "model.generated.ts").write_text(source, encoding="utf-8")


def evaluate(weights: np.ndarray, intercepts: np.ndarray, rows: list[dict[str, str]]) -> dict[str, object]:
    x = matrix(rows)
    probabilities = softmax(x @ weights.T + intercepts)
    predicted_indices = probabilities.argmax(axis=1)
    confidences = probabilities.max(axis=1)
    predicted = [LABELS[index] for index in predicted_indices]
    intent_indices = [index for index, row in enumerate(rows) if row["is_fallback"] == "0"]
    fallback_indices = [index for index, row in enumerate(rows) if row["is_fallback"] == "1"]
    expected = [rows[index]["label"] for index in intent_indices]
    result = {
        "modelVersion": MODEL_VERSION,
        "featureCount": FEATURE_COUNT,
        "trainRows": 1440,
        "heldOutRows": len(rows),
        "intentRows": len(intent_indices),
        "fallbackRows": len(fallback_indices),
        "macroF1": round(macro_f1(expected, [predicted[index] for index in intent_indices]), 4),
        "macroF1Zh": round(macro_f1([rows[index]["label"] for index in intent_indices if rows[index]["locale"] == "zh"], [predicted[index] for index in intent_indices if rows[index]["locale"] == "zh"]), 4),
        "macroF1En": round(macro_f1([rows[index]["label"] for index in intent_indices if rows[index]["locale"] == "en"], [predicted[index] for index in intent_indices if rows[index]["locale"] == "en"]), 4),
        "fallbackRecallAt050": round(sum(confidences[index] < 0.50 for index in fallback_indices) / len(fallback_indices), 4),
        "meanIntentConfidence": round(float(np.mean(confidences[intent_indices])), 4),
        "meanFallbackConfidence": round(float(np.mean(confidences[fallback_indices])), 4),
        "thresholds": {"fallbackBelow": 0.50, "highConfidenceAt": 0.72, "highConfidenceMargin": 0.15},
        "note": "Template-assisted synthetic draft corpus; rows marked template-reviewed require final human language review before formal submission.",
    }
    return result


if __name__ == "__main__":
    train_rows = read_rows(DATA / "train.csv")
    test_rows = read_rows(DATA / "test.csv")
    # Keep ambiguous training rows last so their calibration weight is applied correctly.
    train_rows.sort(key=lambda row: row["is_fallback"] == "1")
    x_train = matrix(train_rows)
    y_train = np.array([LABELS.index(row["label"]) for row in train_rows], dtype=np.int64)
    model_weights, model_intercepts = train(x_train, y_train)
    metrics = evaluate(model_weights, model_intercepts, test_rows)
    export_model(model_weights, model_intercepts)
    metrics_path = ROOT / "docs" / "evidence" / "model-metrics.json"
    metrics_path.parent.mkdir(parents=True, exist_ok=True)
    metrics_path.write_text(json.dumps(metrics, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(metrics, ensure_ascii=False, indent=2))
